### ISSUE TITLE
Multiple Interfaces?  (Documentation unclear.)

### ISSUE THREAD

**Issue by DiagonalArg** [alobbs/macchanger#27]
In the file `/etc/default/macchanger` the variable `ENABLE_INTERFACES` is set to the interface that we want randomized on startup.  If there are more than one interface, it is not clear if we should be providing a space or comma separated list, or something else.  You might indicate in the man page if:

```
macchanger [options] device[ device device ...]
```

or

```
macchanger [options] device[, device, device...]
```

works, or something else.

**Comment by thoger** [comment]
The file `/etc/default/macchanger` is not something supported by upstream macchanger, but is an extension added in distros packaging macchanger.  I see the file in Debian packages, so it's likely in Debian derivates too.

Additionally, the support for `ENABLE_INTERFACES` is apparently currently not implemented:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=780165

If you're using Debian-based distor, the above Debian bug is where to follow-up further.  For other distros, you should raise this in distribution bug tracker.

**Comment by DiagonalArg** [comment]
Thanks!  Will do.
