### ISSUE TITLE
macchanger 1.6.0 lost copying information

### ISSUE THREAD

**Issue by thoger** [alobbs/macchanger#3]
macchanger update form 1.5.0 to 1.6.0 removes COPYING file that contains licensing information.  There's also no license information in the README, so one has to look into all source to find out.

Both GNU and downstream vendor packaging guidelines strongly encourage inclusion of the license text:

http://www.gnu.org/prep/standards/html_node/Releases.html
http://fedoraproject.org/wiki/Packaging:LicensingGuidelines#License_Text

Please consider mentioning license in the README explicitly, in addition to re-adding COPYING, given that current license is GPLv2 or later.

**Comment by alobbs** [comment]
That was unintentional. macchanger 1.7.0 ought to ship the COPYING file again.

**Comment by alobbs** [comment]
https://github.com/alobbs/macchanger/commit/f4f66e1eba1f5154a365d3323088050d0f75a168 fixed it.

**Comment by thoger** [comment]
The commits adds GPL 3 text to `COPYING`, while all source files keep saying GPL 2 or later.  Is this intentional re-license to be GPL 3+?

**Comment by alobbs** [comment]
Yes, it is, indeed. GNU MAC Changer should be distributed under the GPLv3+ from now on.

**Comment by thoger** [comment]
Thank you for the clarification!

**Comment by dpaleino** [comment]
It would be best if this was fixed in the source files too ;)
