### ISSUE TITLE
Issue with macchanger when using BCM43142 wireless card (HP stream 11)

### ISSUE THREAD

**Issue by JayTurtle** [alobbs/macchanger#32]
Hello all. I am a fairly new user to Linux and have been using a virtual machine for the past few months in order to practice. I recently bought myself an HP stream 11 in order to do a fresh install of Kali Linux and try and progress my skills with actual hardware, After many trials and tribulations and a very steep learning curve, namely getting my WiFi card to work properly, I finally managed to set it up. I decided to practice using macchanger as i'm hoping to progress into a Network Security/ PenTesting job role and decided to start off basic. Yet, to no great surprise, I have hit another hurdle. I will post the code below for a better understanding.

`root@kali:~# ifconfig
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 160  bytes 12987 (12.6 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 160  bytes 12987 (12.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.19  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::5b7:6a12:eb0b:8cda  prefixlen 64  scopeid 0x20<link>
        inet6 fdc9:d48e:53e5:0:443c:2c2e:5ce2:984  prefixlen 64  scopeid 0x0<global>
        inet6 2a02:c7d:8017:8200:22bf:364f:35e:a03d  prefixlen 64  scopeid 0x0<global>
        ether XX:XX:XX:XX:XX:XX  txqueuelen 1000  (Ethernet)
        RX packets 27802  bytes 18820989 (17.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 10752
        TX packets 26472  bytes 3586268 (3.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16  

root@kali:~# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 0a5c:216c Broadcom Corp. BCM43142A0 Bluetooth Device
Bus 001 Device 003: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 001 Device 002: ID 05c8:036e Cheng Uei Precision Industry Co., Ltd (Foxlink) Webcam
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
root@kali:~# ifconfig wlan0 down
root@kali:~# macchanger --random wlan0
Current MAC:   XX:XX:XX:XX:XX:XX (unknown)
Permanent MAC: XX:XX:XX:XX:XX:XX (unknown)
[ERROR] Could not change MAC: interface up or insufficient permissions: Too many open files in system`

I get that error message each time and the MAC Addresses stay the same. I have also tried using this method.

`root@kali:~# ifconfig wlan0 down
root@kali:~# ifconfig wlan0
wlan0: flags=4098<BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.0.19  netmask 255.255.255.0  broadcast 192.168.0.255
        ether XX:XX:XX:XX:XX:XX txqueuelen 1000  (Ethernet)
        RX packets 28535  bytes 19040524 (18.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 11715
        TX packets 27111  bytes 3677762 (3.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16  

root@kali:~# ifconfig wlan0 hw ether 0p:6t:j6:7h:o3:r9
0p:6t:j6:7h:o3:r9: invalid ether address.`

Now the latter method i'm not sure if I have even used right as I am a novice. The reason my WiFi adapter is mentioned in the title is that I recall reading on a forum somewhere that some Broadcom cards don't work with macchanger but I can't seem to find any specifics. Please advise.

**Comment by thoger** [comment]
There is an obvious problem in your `ifconfig` invocation clearly indicated by the error message you get: `invalid ether address`.  All digits need to be hex digits.

You can try use `ifconfig` (or `ip`) with correct arguments and see if they fail the same way.  If they do, the problem most likely lies in driver/network device and not `maccahanger`.

`ifconfig wlan0 hw ether 22:33:44:55:66:77`
`ip link set wlan0 address 22:33:44:55:66:77`
