### ISSUE TITLE
macchanger default action should be show

### ISSUE THREAD

**Issue by thoger** [alobbs/macchanger#4]
When macchanger is invoked with no option, only specifying interface name, its default action is to increments interface's MAC by one.  That behavior is not documented, it's likely to overlook the change, and the behavior does not seem very useful.

There were user requests to change default action to --show, and that has been the default in Debian packages for a while, see:

http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=621494

**Comment by thoger** [comment]
Proposed fix: https://github.com/thoger/macchanger/commit/26eda412450f09c4f43961a2e5ac31e92f47d30d

**Comment by alobbs** [comment]
Merged upstream. Thanks @thoger!
