### ISSUE TITLE
Network driver didn't actually change to the new MAC on Realtek Semiconductor Corp

### ISSUE THREAD

**Issue by YerongLi** [alobbs/macchanger#50]
macchanger cannot change MAC address on **Realtek Semiconductor Corp** adapter. Could anyone fix this?

**Comment by MAsghar11** [comment]
@YerongLi , I have a RealTek adapter and am unable to change my MAC address using MAC changer. It says "Network driver didn't actually change to new MAC". Can you tell me how to fix this?
