### ISSUE TITLE
[ERROR] Set device name: No such device

### ISSUE THREAD

**Issue by adomakk** [alobbs/macchanger#71]
Mac changer is not working. I used the command ifconfig to get the device name but when I put the command sudo macchanger - p wlp1s0, I get [ERROR] Set device name: No Such Device. I am using Manjaro Gnome on my computer

**Comment by KDAFOOL** [comment]
I'm also to new to Linux and using the terminal, when I don't use sudo with the command and just put macchanger - p wlp1s0 I get [ERROR] Could not change MAC: Interface up or insufficient permissions: Operation not permitted. When I use sudo that doesn't come up. Is there a way to make so it works without sudo.

**Comment by adomakk** [comment]
Problem solved

**Comment by J35513I5M3** [comment]
what salved the problem?
