### ISSUE TITLE
MAC reverts back after sleep?

### ISSUE THREAD

**Issue by ghost** [alobbs/macchanger#81]
So MAC adress reverts back to perment address after sleep/suspend.

Macchanger runs at @reboot via crontab no problem but reverts back once the computer goes to sleep/suspend.

# **How do I make machanger stay or run after sleep/suspend?**    

I tryed makiong a script 

sudo nano /etc/network/if-up.d/macchange

```ruby
#!/bin/sh

if [ "$IFACE" = lo ]; then
        exit 0
fi

/usr/bin/macchanger -r wlp2s0
```
and made it executable but didn't fix the issue.

**Comment by streamdp** [comment]
Hi @CyberPunkInterface, 
look this [issue #83](https://github.com/alobbs/macchanger/issues/83#issuecomment-966550888).

**Comment by ghost** [comment]
Thanks, @streamdp 

Editing the `/etc/default/macchanger` and adding `ENABLE_ON_POST_UP_DOWN=true` and adding my interface name `wlp2s0` seemed to help.

## I forgot to Add that Macchanger was being managed at boot via crontab.
