### ISSUE TITLE
FEATURE REQUEST: generate and display (only) a random MAC

### ISSUE THREAD

**Issue by ladar** [alobbs/macchanger#88]
I already have scripts to rotate my MAC address, what I need is a good way of generating a new random MAC.

Unfortunately the access point at the coffee shop seems to reject completely random addresses. So I just need something that will spit out a valid replacement address - preferably with the ability to have the vendor portion match an existing NIC (if provided), or a specific vendor (if provided). 

Thanks.

**Comment by JonnyTech** [comment]
https://github.com/andrewgho/genmac

**Comment by ladar** [comment]
Hi @JonnyTech ... thanks.
